// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jfirspguolaurlbynxrs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmaXJzcGd1b2xhdXJsYnlueHJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5NjE5NjQsImV4cCI6MjA3MDUzNzk2NH0.KwvUoug3vRbLvWDcl6v9HZ7xlN_7z0AXth8EU2A_hxU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});